Repository sulu/skeleton, pull requests merged in 2020-02, with the labels that each got.

#33 Adjust explanation of SULU_ADMIN_EMAIL environment variable
  .env
Labels: enhancement

#22 Add example configuration for jackrabbit
  config/packages/sulu_document_manager.yaml
Labels: documentation

#35 Fix compatibility to php 7.4
  .travis.yml
  composer.json
Labels: bug
